name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Command used
        2. Input provided
        3. Output observed
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v1.0.0
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g., 18.19.0
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell 